-- Seed data for OSDR
TRUNCATE osdr_items RESTART IDENTITY CASCADE;

INSERT INTO osdr_items (dataset_id, title, organism, study_type, status, updated_at, raw) VALUES
('OSD-37', 'Spaceflight-induced Molecular Changes in Mouse Brain', 'Mus musculus', 'Transcriptomics', 'Active', NOW() - INTERVAL '2 days', '{"accession": "OSD-37", "doi": "10.26030/example1"}'),
('OSD-48', 'Gene Expression in Arabidopsis Under Microgravity', 'Arabidopsis thaliana', 'RNA Sequencing', 'Active', NOW() - INTERVAL '5 days', '{"accession": "OSD-48", "doi": "10.26030/example2"}'),
('OSD-120', 'Caenorhabditis elegans Muscle Development in Space', 'Caenorhabditis elegans', 'Proteomics', 'Completed', NOW() - INTERVAL '10 days', '{"accession": "OSD-120", "doi": "10.26030/example3"}'),
('OSD-169', 'Immune System Response in Astronauts During Long-Duration Spaceflight', 'Homo sapiens', 'Immunology', 'Active', NOW() - INTERVAL '1 day', '{"accession": "OSD-169", "doi": "10.26030/example4"}'),
('OSD-205', 'Microbial Communities on ISS Surfaces Over Time', 'Bacteria', 'Metagenomics', 'Active', NOW() - INTERVAL '3 days', '{"accession": "OSD-205", "doi": "10.26030/example5"}'),
('OSD-242', 'Bone Density Changes in Rodents During Spaceflight', 'Rattus norvegicus', 'Bone Biology', 'Completed', NOW() - INTERVAL '15 days', '{"accession": "OSD-242", "doi": "10.26030/example6"}'),
('OSD-289', 'Cardiac Function in Microgravity Conditions', 'Mus musculus', 'Cardiovascular', 'Active', NOW() - INTERVAL '7 days', '{"accession": "OSD-289", "doi": "10.26030/example7"}'),
('OSD-316', 'Plant Growth Responses to Cosmic Radiation', 'Zea mays', 'Plant Biology', 'Active', NOW() - INTERVAL '4 days', '{"accession": "OSD-316", "doi": "10.26030/example8"}'),
('OSD-347', 'Yeast Cell Division in Space Environment', 'Saccharomyces cerevisiae', 'Cell Biology', 'Completed', NOW() - INTERVAL '20 days', '{"accession": "OSD-347", "doi": "10.26030/example9"}'),
('OSD-398', 'Drosophila Development and Aging in Microgravity', 'Drosophila melanogaster', 'Developmental Biology', 'Active', NOW() - INTERVAL '6 days', '{"accession": "OSD-398", "doi": "10.26030/example10"}'),
('OSD-421', 'Algae Photosynthesis Under Space Conditions', 'Chlorella vulgaris', 'Photosynthesis', 'Active', NOW() - INTERVAL '8 days', '{"accession": "OSD-421", "doi": "10.26030/example11"}'),
('OSD-456', 'Nematode Behavior and Neural Activity in Zero Gravity', 'Caenorhabditis elegans', 'Neuroscience', 'Completed', NOW() - INTERVAL '25 days', '{"accession": "OSD-456", "doi": "10.26030/example12"}'),
('OSD-489', 'Fungal Growth on ISS Materials', 'Aspergillus niger', 'Mycology', 'Active', NOW() - INTERVAL '12 days', '{"accession": "OSD-489", "doi": "10.26030/example13"}'),
('OSD-512', 'Bacterial Antibiotic Resistance in Space', 'Escherichia coli', 'Microbiology', 'Active', NOW() - INTERVAL '5 days', '{"accession": "OSD-512", "doi": "10.26030/example14"}'),
('OSD-537', 'Tomato Cultivation in Microgravity', 'Solanum lycopersicum', 'Agriculture', 'Active', NOW() - INTERVAL '9 days', '{"accession": "OSD-537", "doi": "10.26030/example15"}'),
('OSD-568', 'Tissue Engineering in Space Conditions', 'Homo sapiens', 'Tissue Engineering', 'Active', NOW() - INTERVAL '11 days', '{"accession": "OSD-568", "doi": "10.26030/example16"}'),
('OSD-594', 'Zebrafish Embryo Development During Spaceflight', 'Danio rerio', 'Embryology', 'Completed', NOW() - INTERVAL '18 days', '{"accession": "OSD-594", "doi": "10.26030/example17"}'),
('OSD-623', 'Soil Microbiome Analysis for Lunar Agriculture', 'Soil microbiota', 'Astrobiology', 'Active', NOW() - INTERVAL '13 days', '{"accession": "OSD-623", "doi": "10.26030/example18"}'),
('OSD-651', 'Protein Crystal Growth in Microgravity', 'Various', 'Crystallography', 'Active', NOW() - INTERVAL '16 days', '{"accession": "OSD-651", "doi": "10.26030/example19"}'),
('OSD-682', 'Radiation Effects on Human Cells in Deep Space Simulation', 'Homo sapiens', 'Radiation Biology', 'Active', NOW() - INTERVAL '14 days', '{"accession": "OSD-682", "doi": "10.26030/example20"}'),
('OSD-715', 'Soybean Nitrogen Fixation in Reduced Gravity', 'Glycine max', 'Plant Physiology', 'Active', NOW() - INTERVAL '21 days', '{"accession": "OSD-715", "doi": "10.26030/example21"}'),
('OSD-748', 'Stem Cell Differentiation Under Microgravity', 'Homo sapiens', 'Stem Cell Research', 'Active', NOW() - INTERVAL '17 days', '{"accession": "OSD-748", "doi": "10.26030/example22"}'),
('OSD-781', 'Bacterial Biofilm Formation on Spacecraft Materials', 'Pseudomonas aeruginosa', 'Microbiology', 'Completed', NOW() - INTERVAL '30 days', '{"accession": "OSD-781", "doi": "10.26030/example23"}'),
('OSD-812', 'Moss Growth and Reproduction in Space Environment', 'Physcomitrella patens', 'Plant Biology', 'Active', NOW() - INTERVAL '22 days', '{"accession": "OSD-812", "doi": "10.26030/example24"}'),
('OSD-843', 'Muscle Atrophy Mechanisms in Astronauts', 'Homo sapiens', 'Muscle Biology', 'Active', NOW() - INTERVAL '19 days', '{"accession": "OSD-843", "doi": "10.26030/example25"}'),
('OSD-876', 'Wheat Seed Germination in Lunar Regolith Simulant', 'Triticum aestivum', 'Agriculture', 'Active', NOW() - INTERVAL '24 days', '{"accession": "OSD-876", "doi": "10.26030/example26"}'),
('OSD-905', 'Probiotic Bacteria Viability During Spaceflight', 'Lactobacillus', 'Microbiology', 'Active', NOW() - INTERVAL '26 days', '{"accession": "OSD-905", "doi": "10.26030/example27"}'),
('OSD-934', 'Spider Web Construction in Zero Gravity', 'Arachnida', 'Behavioral Science', 'Completed', NOW() - INTERVAL '35 days', '{"accession": "OSD-934", "doi": "10.26030/example28"}'),
('OSD-967', 'Vaccine Stability in Space Conditions', 'Various', 'Pharmaceutical', 'Active', NOW() - INTERVAL '28 days', '{"accession": "OSD-967", "doi": "10.26030/example29"}'),
('OSD-992', 'Tardigrade Survival in Extreme Space Conditions', 'Tardigrada', 'Astrobiology', 'Active', NOW() - INTERVAL '31 days', '{"accession": "OSD-992", "doi": "10.26030/example30"}'),
('OSD-1024', 'Red Blood Cell Changes in Microgravity', 'Homo sapiens', 'Hematology', 'Active', NOW() - INTERVAL '23 days', '{"accession": "OSD-1024", "doi": "10.26030/example31"}'),
('OSD-1056', 'Lettuce Cultivation for ISS Food Production', 'Lactuca sativa', 'Agriculture', 'Active', NOW() - INTERVAL '27 days', '{"accession": "OSD-1056", "doi": "10.26030/example32"}'),
('OSD-1089', 'Mitochondrial Function in Space-Exposed Cells', 'Mus musculus', 'Cell Biology', 'Active', NOW() - INTERVAL '29 days', '{"accession": "OSD-1089", "doi": "10.26030/example33"}'),
('OSD-1121', 'Virus Reactivation in Astronauts', 'Homo sapiens', 'Virology', 'Active', NOW() - INTERVAL '32 days', '{"accession": "OSD-1121", "doi": "10.26030/example34"}'),
('OSD-1154', 'Brine Shrimp Development in Microgravity', 'Artemia salina', 'Developmental Biology', 'Completed', NOW() - INTERVAL '40 days', '{"accession": "OSD-1154", "doi": "10.26030/example35"}'),
('OSD-1187', 'Cannabis Plant Growth for Medicinal Research in Space', 'Cannabis sativa', 'Pharmacology', 'Active', NOW() - INTERVAL '33 days', '{"accession": "OSD-1187", "doi": "10.26030/example36"}'),
('OSD-1219', 'Gut Microbiome Changes During Long Missions', 'Homo sapiens', 'Metagenomics', 'Active', NOW() - INTERVAL '25 days', '{"accession": "OSD-1219", "doi": "10.26030/example37"}'),
('OSD-1252', 'Fern Spore Germination in Space', 'Ceratopteris richardii', 'Plant Biology', 'Active', NOW() - INTERVAL '36 days', '{"accession": "OSD-1252", "doi": "10.26030/example38"}'),
('OSD-1285', 'DNA Repair Mechanisms in Space Radiation', 'Homo sapiens', 'Genetics', 'Active', NOW() - INTERVAL '34 days', '{"accession": "OSD-1285", "doi": "10.26030/example39"}'),
('OSD-1318', 'Oyster Mushroom Cultivation on ISS', 'Pleurotus ostreatus', 'Mycology', 'Active', NOW() - INTERVAL '38 days', '{"accession": "OSD-1318", "doi": "10.26030/example40"}'),
('OSD-1351', 'Bone Marrow Changes in Microgravity', 'Mus musculus', 'Hematology', 'Active', NOW() - INTERVAL '37 days', '{"accession": "OSD-1351", "doi": "10.26030/example41"}'),
('OSD-1384', 'Cyanobacteria Oxygen Production for Life Support', 'Synechococcus', 'Astrobiology', 'Active', NOW() - INTERVAL '39 days', '{"accession": "OSD-1384", "doi": "10.26030/example42"}'),
('OSD-1417', 'Eye Pressure and Vision Changes in Astronauts', 'Homo sapiens', 'Ophthalmology', 'Active', NOW() - INTERVAL '41 days', '{"accession": "OSD-1417", "doi": "10.26030/example43"}'),
('OSD-1450', 'Rice Growth in Microgravity Conditions', 'Oryza sativa', 'Agriculture', 'Active', NOW() - INTERVAL '42 days', '{"accession": "OSD-1450", "doi": "10.26030/example44"}'),
('OSD-1483', 'Antibiotic Production by Streptomyces in Space', 'Streptomyces', 'Pharmaceutical', 'Completed', NOW() - INTERVAL '45 days', '{"accession": "OSD-1483", "doi": "10.26030/example45"}'),
('OSD-1516', 'Nerve Cell Growth and Connectivity in Zero Gravity', 'Homo sapiens', 'Neuroscience', 'Active', NOW() - INTERVAL '43 days', '{"accession": "OSD-1516", "doi": "10.26030/example46"}'),
('OSD-1549', 'Pea Plant Nodulation and Growth in Space', 'Pisum sativum', 'Plant Biology', 'Active', NOW() - INTERVAL '44 days', '{"accession": "OSD-1549", "doi": "10.26030/example47"}'),
('OSD-1582', 'Chromosomal Stability in Space-Exposed Cells', 'Homo sapiens', 'Genetics', 'Active', NOW() - INTERVAL '46 days', '{"accession": "OSD-1582", "doi": "10.26030/example48"}'),
('OSD-1615', 'Spirulina Biomass Production for Space Food', 'Spirulina platensis', 'Astrobiology', 'Active', NOW() - INTERVAL '47 days', '{"accession": "OSD-1615", "doi": "10.26030/example49"}'),
('OSD-1648', 'Liver Function Changes During Spaceflight', 'Homo sapiens', 'Hepatology', 'Active', NOW() - INTERVAL '48 days', '{"accession": "OSD-1648", "doi": "10.26030/example50"}');

SELECT COUNT(*) as total_records FROM osdr_items;
